#!/bin/bash

echo [-] Checking distribution
distro=`lsb_release -si`
if [ "$distro" == "Ubuntu" ]
then
    echo [+] Ubuntu detected!
    echo [+] Installing dependencies...
    apt-get install libterm-readkey-perl libwww-mechanize-perl
    echo [+] Copying executable
    cp netgearstat /usr/bin
    echo [+] Installation complete!
    echo Run with: bash-prompt~$ netgearstat <router_ip_address> <username>
else
    echo [-] This is not a ubuntu install, please install dependencies manually
    echo -e "[-] Dependencies are: \n\t HTML::TreeBuilder \n\t Term::ReadKey \n\t WWW::Mechanize"
fi
